// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 14fdf827f8911e3b732ae9b9bfdb38bad0c92209a14d92ac96161fad304b3ae7
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package v1

import (
	"encoding/binary"

	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BidTrace) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BidTrace) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BidTrace)
	}
	{ // Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, t.Slot)
	}
	{ // Field #1 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Field #2 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Field #3 'BuilderPubkey'
		dst = append(dst, t.BuilderPubkey[:48]...)
	}
	{ // Field #4 'ProposerPubkey'
		dst = append(dst, t.ProposerPubkey[:48]...)
	}
	{ // Field #5 'ProposerFeeRecipient'
		dst = append(dst, t.ProposerFeeRecipient[:20]...)
	}
	{ // Field #6 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Field #7 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Field #8 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		for i := range 4 {
			dst = binary.LittleEndian.AppendUint64(dst, t[i])
		}
	}
	return dst, nil
}

func (t *BidTrace) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 236 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'ParentHash' (static)
		buf := buf[8:40]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #2 'BlockHash' (static)
		buf := buf[40:72]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #3 'BuilderPubkey' (static)
		buf := buf[72:120]
		copy(t.BuilderPubkey[:], buf)
	}
	{ // Field #4 'ProposerPubkey' (static)
		buf := buf[120:168]
		copy(t.ProposerPubkey[:], buf)
	}
	{ // Field #5 'ProposerFeeRecipient' (static)
		buf := buf[168:188]
		copy(t.ProposerFeeRecipient[:], buf)
	}
	{ // Field #6 'GasLimit' (static)
		buf := buf[188:196]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasUsed' (static)
		buf := buf[196:204]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'Value' (static)
		buf := buf[204:236]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		for i := range 4 {
			buf := buf[8*i : 8*(i+1)]
			val1[i] = binary.LittleEndian.Uint64(buf)
		}
		t.Value = val1
	}
	return nil
}

func (t *BidTrace) SizeSSZ() (size int) {
	return 236
}

func (t *BidTrace) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BidTrace) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BidTrace)
	}
	idx := hh.Index()
	{ // Field #0 'Slot'
		hh.PutUint64(t.Slot)
	}
	{ // Field #1 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #2 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #3 'BuilderPubkey'
		hh.PutBytes(t.BuilderPubkey[:48])
	}
	{ // Field #4 'ProposerPubkey'
		hh.PutBytes(t.ProposerPubkey[:48])
	}
	{ // Field #5 'ProposerFeeRecipient'
		hh.PutBytes(t.ProposerFeeRecipient[:20])
	}
	{ // Field #6 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #7 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #8 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return err
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	hh.Merkleize(idx)
	return nil
}
