// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fa67aaf7fc65702aa775b204cc5192980c98d0e6e502defcec90314cc362c74f
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package v1

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedValidatorRegistrations) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedValidatorRegistrations) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	dstlen := len(dst)
	// Offset #0 'Registrations'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Registrations'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Registrations
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	return dst, nil
}

func (t *SignedValidatorRegistrations) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Registrations' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrOffset
	}
	{ // Field #0 'Registrations' (dynamic)
		buf := buf[offset0:]
		val1 := t.Registrations
		itemCount := len(buf) / 180
		if len(buf)%180 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			if val1[i] == nil {
				val1[i] = new(SignedValidatorRegistration)
			}
			buf := buf[180*i : 180*(i+1)]
			if err = val1[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.Registrations = val1
	}
	return nil
}

func (t *SignedValidatorRegistrations) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	// Field #0 'Registrations' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Registrations'
		size += len(t.Registrations) * 180
	}
	return size
}

func (t *SignedValidatorRegistrations) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SignedValidatorRegistrations) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	idx := hh.Index()
	{ // Field #0 'Registrations'
		t := t.Registrations
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
