// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: c54f24188a262444dacfb91ce046b72770c87a5e2482faebaa001e733ec6f529
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package bellatrix

import (
	"encoding/binary"

	"github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/bellatrix"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SubmitBlockRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SubmitBlockRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	dstlen := len(dst)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	// Offset #1 'ExecutionPayload'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #1 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(bellatrix.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *SubmitBlockRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 336 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:236]
		if t.Message == nil {
			t.Message = new(v1.BidTrace)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	// Field #1 'ExecutionPayload' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[236:240]))
	if offset1 != 336 {
		return sszutils.ErrOffset
	}
	{ // Field #2 'Signature' (static)
		buf := buf[240:336]
		copy(t.Signature[:], buf)
	}
	{ // Field #1 'ExecutionPayload' (dynamic)
		buf := buf[offset1:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(bellatrix.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *SubmitBlockRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	// Field #0 'Message' static (236 bytes)
	// Field #1 'ExecutionPayload' offset (4 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 336
	{ // Dynamic field #1 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	return size
}

func (t *SubmitBlockRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SubmitBlockRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(bellatrix.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
