// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fd193b503ede825747d85a6a92f14c6f6e365fbf4ac580018e8826da8697f9d8
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BuilderBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BuilderBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset #0 'Header'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		for i := range 4 {
			dst = binary.LittleEndian.AppendUint64(dst, t[i])
		}
	}
	{ // Field #2 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(capella.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *BuilderBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 84 {
		return sszutils.ErrOffset
	}
	{ // Field #1 'Value' (static)
		buf := buf[4:36]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		for i := range 4 {
			buf := buf[8*i : 8*(i+1)]
			val1[i] = binary.LittleEndian.Uint64(buf)
		}
		t.Value = val1
	}
	{ // Field #2 'Pubkey' (static)
		buf := buf[36:84]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:]
		if t.Header == nil {
			t.Header = new(capella.ExecutionPayloadHeader)
		}
		if err = t.Header.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *BuilderBid) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'Value' static (32 bytes)
	// Field #2 'Pubkey' static (48 bytes)
	size += 84
	{ // Dynamic field #0 'Header'
		size += t.Header.SizeSSZ()
	}
	return size
}

func (t *BuilderBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BuilderBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.Index()
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(capella.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return err
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
