// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ab2fdf1ab6c4c919ba63fee9c8dfcc1c429da089d08a630485c97128cbfe8aed
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadAndBlobsBundle) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadAndBlobsBundle) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	dstlen := len(dst)
	// Offset #0 'ExecutionPayload'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #1 'BlobsBundle'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Dynamic Field #1 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadAndBlobsBundle) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrOffset
	}
	// Field #1 'BlobsBundle' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(deneb.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'BlobsBundle' (dynamic)
		buf := buf[offset1:]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if err = t.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *ExecutionPayloadAndBlobsBundle) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlobsBundle' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #1 'BlobsBundle'
		size += t.BlobsBundle.SizeSSZ()
	}
	return size
}

func (t *ExecutionPayloadAndBlobsBundle) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ExecutionPayloadAndBlobsBundle) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	idx := hh.Index()
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	hh.Merkleize(idx)
	return nil
}
