// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6f7a41fef49a7dee6d4b6ecf3987ffd57dc6e0e90a53cc9ac1560be9c2cfdf94
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BuilderBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BuilderBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset #0 'Header'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #1 'BlobKZGCommitments'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #2 'ExecutionRequests'
	offset2 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		for i := range 4 {
			dst = binary.LittleEndian.AppendUint64(dst, t[i])
		}
	}
	{ // Field #4 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Dynamic Field #1 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = append(dst, t[i][:48]...)
		}
	}
	{ // Dynamic Field #2 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[offset2:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *BuilderBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 92 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 92 {
		return sszutils.ErrOffset
	}
	// Field #1 'BlobKZGCommitments' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	// Field #2 'ExecutionRequests' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #3 'Value' (static)
		buf := buf[12:44]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		for i := range 4 {
			buf := buf[8*i : 8*(i+1)]
			val1[i] = binary.LittleEndian.Uint64(buf)
		}
		t.Value = val1
	}
	{ // Field #4 'Pubkey' (static)
		buf := buf[44:92]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:offset1]
		if t.Header == nil {
			t.Header = new(deneb.ExecutionPayloadHeader)
		}
		if err = t.Header.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'BlobKZGCommitments' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for i := range itemCount {
			buf := buf[48*i : 48*(i+1)]
			copy(val2[i][:], buf)
		}
		t.BlobKZGCommitments = val2
	}
	{ // Field #2 'ExecutionRequests' (dynamic)
		buf := buf[offset2:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = t.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *BuilderBid) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'BlobKZGCommitments' offset (4 bytes)
	// Field #2 'ExecutionRequests' offset (4 bytes)
	// Field #3 'Value' static (32 bytes)
	// Field #4 'Pubkey' static (48 bytes)
	size += 92
	{ // Dynamic field #0 'Header'
		size += t.Header.SizeSSZ()
	}
	{ // Dynamic field #1 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	{ // Dynamic field #2 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	return size
}

func (t *BuilderBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BuilderBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.Index()
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.PutBytes(t[i][:48])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return err
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #4 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
